### ISSUE TITLE
See the config file that is opened in webviz-ert

### ISSUE THREAD

**Issue by hnformentin** [equinor/webviz-ert#379] opened 2022-08-18 13:37 UTC
**Is your feature request related to a problem? Please describe.**
It is probably useful to know which case is opened in webviz ert, as we have when we plot directly in the gui.

**Describe the solution you'd like**
The name of the config file could be on the top of the page or in the panel of the right, where we select between the different views.

**Comment by oysteoh** [comment] 2022-08-19 06:47
Duplicate of #351

**Closed** 2022-08-19 06:47 UTC
