### ISSUE TITLE
Adress flakiness in test_axes_labels

### ISSUE THREAD

**Issue by hnformentin** [equinor/webviz-ert#297] opened 2022-06-29 07:22 UTC
**Describe the bug**
There is a flakiness associated with test_axes_labels. It fails randonly, particularly in Github Actions.
Check https://ci.equinor.com/scout/job/komodo_testing/job/webviz-ert-pr/334/console .

**Comment by oysteoh** [comment] 2022-07-05 07:03
Not been able to reproduce lately - will monitor a bit more before closing this issue

**Comment by hnformentin** [comment] 2022-07-08 10:56
In #310 mypy is failing on the pipeline but all tests are passing locally.
Could we add an automatic check of mypy locally, similarly to `test_formatting`?

**Comment by oysteoh** [comment] 2022-07-08 11:36
i'm not sure if that is what is done in other repositories? But if that is a standard thing to do i guess we can add it as well 👍

**Comment by valentin-krasontovitsch** [comment] 2022-07-11 07:56
I think that's a good idea - I would tend to put it into a git hook, like before you push, run tests, run mypy, run formatting check, ... but git hooks are (a bit) difficult to distribute, and maybe not everybody wants to have it as part of their push process (especially when the whole test suite take a long time to run). putting it as part of tests will give us quick feedback when mypy fails, and it can easily be checked locally without having to remember to run yet another command!
but i am also not sure about how much "standard" this is. I guess maybe we could discuss it in a separate PR / during a stand up? or just push it in as long as it's vacation time and people are gone ; )

**Comment by oysteoh** [comment] 2022-07-11 11:03
we are not distributing git hooks as this is personal preferences . Let us discuss in a separate issue - i'll close this now.

**Comment by hnformentin** [comment] 2022-08-05 07:47
[It seems that flakiness was observed in Jenkins job :
](https://equinor.slack.com/archives/CKC3H3W74/p1659681680258459)

I suggest to replace the test of the dom element to a test of the function `def axis_label_for_ensemble_response`. It could be simplified to make a test simplier, for example:

`def axis_label_for_ensemble_response(
    ensemble_name: str, response_name: str, response_data_index: Any, #Union(Index, pd.Int64Index),
) -> str:`

**Comment by valentin-krasontovitsch** [comment] 2022-08-05 07:58
i feel a bit of internal resistance to scraping the user interface / frontend test. i do prefer to test the behaviour, and it's already written... and what does it mean in principle? if we cannot rely on finding an element that is part of a plot, then we can probably delete most of our current frontend tests : ( of course it begs the question why seemingly mostly this test or this particular check produces errors. I have been seeing one other type of error as well though, which was just flakiness. maybe i can make a new issue and mention it here...

I would much prefer to fix the flakiness, ideally. of course, if we don't manage that, then ... we can get rid of this test.

now about fixing the flakiness - honestly, i don't know what to do X( we already call wait_a_bit before that check, and i figure dash also has a timeout - i would really like to do a deepdive into this, be able to replicate it reliably, and understand in detail what is happening and why (in my experience) automated browser stuff is always flaky. that sounds a bit far-fetched though. but there should be front-end people that can answer this stuff! maybe i can ask in the developer community in the equinor slack, if anybody has experience with this.
of course as a simple workaround we can increase the time of `wait_a_bit`, and see if that helps...

**Comment by valentin-krasontovitsch** [comment] 2022-08-08 11:04
seems like a solution was found, we'll have to wait for it to get merged and see if the komodo build starts passing. could not reproduce in github actions or jenkins though... see PR #358  for more details

**Closed** 2022-08-09 07:44 UTC
Labels: bug
